### ISSUE TITLE
Backend Technology

### ISSUE THREAD

**Issue by almeidaalex** [OddaDigitalSystem/full-stack-challenge#1]
Hello, 
I've a question about **requirements** and **tips**:
- On requirements sections, it's written *Main programming language is Javascript/Typescript*, so backend should be written using js/ts?
- And on Tips sections says *You are free to choose how you will do your backend.* in that manner I'm free to use any approach or technology as ruby for example?

So I'm confusing about the main programming language and how I'll do the backend.

Thank you.

**Comment by rhuanbarreto** [comment]
Backend is free to choose. Frontend must be in JavaScript/TypeScript and React.
